# Site settings
title: matt battison
description: >-
  Matt Battison's blog.
url: "https://mattbattison.co.uk"

# Social media
email: hello@mattbattison.co.uk
twitter_username: mattbattison
github_username:  mattbattison

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
