# Site settings
title: matt battison
description: >-
  Matt Battison's blog.
url: "https://mattbattison.dev"

# Social media
email: hello@mattbattison.dev
twitter_username: mattbattison
github_username:  mattbattison
instagram_username: mattbattison

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Excludes
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - README.md
