# Site settings
title: matt battison
description: >-
  Matt Battison's blog.
url: "https://mattbattison.uk"

# Social media
email: hello@mattbattison.uk
twitter_username: mattbattison
github_username:  mattbattison
instagram_username: mattbattison

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
